<?xml version="1.0"?>
<project xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd" xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.bigdata.platform</groupId>
    <artifactId>scheduler-web</artifactId>
    <version>1.0.0-SNAPSHOT</version>
  </parent>
  <artifactId>scheduler-web-client</artifactId>
  <version>1.1.0-SNAPSHOT</version>
  <name>scheduler-web-client</name>
  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
  </properties>

	<dependencies>
        <dependency>
            <groupId>com.bigdata.platform</groupId>
            <artifactId>scheduler-common</artifactId>
        </dependency>
	</dependencies>

    <!-- 显示源码 -->
    <build>
        <plugins>
            <plugin>
                <artifactId>maven-source-plugin</artifactId>
                <version>3.0.1</version>
                <configuration>
                    <attach>true</attach>
                </configuration>
                <executions>
                    <execution>
                        <phase>compile</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
