spring:
  datasource:
    druid:
      driver-class-name: net.sf.log4jdbc.DriverSpy
      web-stat-filter:
        enabled: false
    url: jdbc:log4jdbc:mysql://10.60.156.93:3306/scheduler
    username: zg
    password: zg123456
    type: com.alibaba.druid.pool.DruidDataSource
  #上传限制文件大小
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 8090
  
zookeeper:
  quorum: 10.60.156.93:2181
  
logging:
  path: /home/ubuntu/opt/scheduler-web
  level: 
    root: info


## kafka_hive集群的id
db:
  id: 295

club-boot:
   server:
      env: test

## 公共配置
data:
  upload:
    basedir:
      path: /tmp/scheduler/upload
  download:
    basedir:
      path: /tmp/scheduler/download
  storage:
    dfs:
      base-path: /data_platform/scheduler-data-pre

fs:
  defaultFS: s3a://cfdp-new
  s3a:
    endpoint: s3.us-west-2.amazonaws.com
    access:
      key:
    secret:
      key:
    connection:
      maximum: 100
      establish:
        timeout: 5000 # 单位:ms
      timeout: 200000 # 单位:ms
    attempts:
      maximum: 20
    threads:
      max: 10
      keepalivetime: 60 #单位:s
  oss:
    endpoint:
    access-key-id:
    access-key-secret:
    security-token:
    multipart:
      download:
        size:           # 102400

hadoop:
  kerberos:
    authentication:
      enable: false

java:
  security:
    krb5:
      conf:
        path: /etc/krb5.conf
login:
  user:
    keytab:
      username: hdfs@EMR.COM
      path: /opt/hdfs.keytab

scheduler:
  env:
    path:

#python3执行路径
python3:
  path:
    exec: /usr/bin/python3

dqc:
  log-url:
    base-path: http://gaia.us-test.huoli101.com/#/app/task-management/log-view
    
