package com.zhugeio.platform.sqlparser.spark.enums;

public enum SparkStmtType {

    UNKNOWN,
    DESC_DATABASE,

    CREATE_TABLE,
    CREATE_TABLE_AS_SELECT,
    CREATE_TABLE_AS_LIKE,
    DROP_TABLE,
    TRUNCATE_TABLE,
    READ_TABLE,
    MERGE_TABLE,
    REFRESH_TABLE,
    LOAD_TEMP_TABLE,
    EXPORT_TABLE,
    ANALYZE_TABLE,

    ALTER_TABLE_RENAME,
    ALTER_TABLE_ADD_COLS,
    ALTER_TABLE_PROPERTIES,
    ALTER_TABLE_RENAME_COL,
    ALTER_TABLE_DROP_PARTS,
    ALTER_TABLE_ADD_PARTS,
    ALTER_TABLE_RENAME_PART,
    ALTER_TABLE_SET_LOCATION,
    DESC_TABLE,
    MSCK_TABLE,

    SELECT,
    INSERT_VALUES,
    INSERT_SELECT,
    MULTI_INSERT,

    CREATE_VIEW,
    DROP_VIEW,
    ALTER_VIEW_QUERY,
    ALTER_VIEW_RENAME,
    ALTER_VIEW_PROPERTIES,

    SHOW, //mysql 命令
    SHOW_COLUMNS,
    SHOW_PARTITIONS,
    SHOW_TABLES,
    SHOW_TABLE,
    SHOW_TABLE_PROPERTIES,
    SHOW_CREATE_TABLE,

    SHOW_FUNCTIONS,
    DESC_FUNCTION,

    //LIST_JARS,
    //DELETE_JAR,

    KILL,
    STATUS,
    ADDJAR,
    ANGEL,

    CACHE,
    UNCACHE,
    CLEAR_CACHE,

    COMPRESS_TABLE,
    COMPRESS_FILE,

    DISTCP_DRUID,

    EXPLAIN

}
